### PR TITLE
Following a common standard

### PR DESCRIPTION
**Pull request by Turupawn**
Changes:
- Added a `metadata/` and `images/` folder
- Removed the `.json` file extension

This is to make it easier to comply to the latest default URI generator by OpenZeppelin
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L92

Cheers!

### CODE REVIEW

**Comment by STYJ** [comment]
Nice, I've been planning to write a script to split the metadata.json into their individual json files.

**Comment by Turupawn** [comment]
Great to hear! Thank you for creating this!

**Comment by Turupawn** [comment]
Feel free to merge or just grab ideas and close this PR but please let me know so I can create a youtube video about this. I'm sure that people will find a lot of value from this

**Comment by STYJ** [comment]
You must have misunderstood haha, I'm not the person who created this repo, just another user!

**Comment by Turupawn** [comment]
lol

**Comment by NotLuksus** [comment]
Could you create an input using iquirer asking the user if they want it in one or in multiple files

**Comment by Turupawn** [comment]
> Could you create an input using iquirer asking the user if they want it in one or in multiple files

Sure! I can do it

**Comment by Turupawn** [comment]
@NotLuksus Just added the iquirer

**Comment by Turupawn** [comment]
And btw, after the other PR was merged it started asking for a minimist library
`Cannot find module 'minimist'`
So I had to `npm install minimist`
Can you please add it to the dependency list?

Other than that it looks ready to go for me, again please let me know what you think.

**Comment by NotLuksus** [comment]
Thank you for the contribution, will add minimist to the dependency list!

**Pull request merged**
