### PR TITLE
Add total supply of nft and different rarities

### PR DESCRIPTION
**Pull request by devstar0718**
Hi, I updated the code to input total supply of NFT and provide different rarities
Hope it to be improve this repo for users.

### CODE REVIEW

**Comment by debofxe** [comment]
hello, pls did you by chance create a tutorial on how to use it now?

**Comment by devstar0718** [comment]
can you please try to run my updates?
It will be asking all information needed.
or I can upload some tutorial video?

**Comment by debofxe** [comment]
I tried to run it but it looked thesame thing as the original.

**Comment by debofxe** [comment]
or is there a different way to run your update? because its not asking me for total supply.

**Comment by devstar0718** [comment]
Please check line 90 and 241 on my updates (index.js)
what's your whatsapp or telegram?
Let's have a quick call

**Comment by devstar0718** [comment]
+18152165330 - whatsapp
@devstar0718 - telegram
devstar0718@gmail.com - email
this is my contact info

**Pull request merged**
